"""add reader_id

Revision ID: 2185c2a46572
Revises: 
Create Date: 2025-09-27 17:01:49.303909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2185c2a46572'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Books', sa.Column('reader_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Books', 'users', ['reader_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Books', type_='foreignkey')
    op.drop_column('Books', 'reader_id')
    # ### end Alembic commands ###
